title: Gearface
theme: minima
author: fizzypop1868
email: spyles09@mail.bw.edu
description: > # this means to ignore newlines until "baseurl:"
  If you wanna git to Mars, make friends with some bugs first 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  fizzypop1868 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
